version: '3.8'

services:
  vcpkg-harbor:
    build: .
    ports:
      - "15151:15151"
    environment:
      - VCPKG_HOST=0.0.0.0
      - VCPKG_PORT=15151
      - VCPKG_WORKERS=4
      - VCPKG_MINIO_ENDPOINT=minio:9000
      - VCPKG_MINIO_ACCESS_KEY=minioadmin
      - VCPKG_MINIO_SECRET_KEY=minioadmin
      - VCPKG_MINIO_BUCKET=vcpkg-harbor
      - VCPKG_MINIO_SECURE=false
      - VCPKG_LOG_LEVEL=INFO
      - VCPKG_LOG_JSON=true
    volumes:
      - ./logs:/app/logs
    depends_on:
      - minio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15151/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  minio_data: